proc-macro = true

[package]
name = "input_reader_derive"
version = "0.1.0"
authors = ["Evgeny Shavlyugin <eshavlyugin@gmail.com>"]

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = "1.0"
quote = "1.0"
